name: e_commerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  flutter_image_compress: ^2.3.0
  lottie: ^3.1.2
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.2.0
  connectivity_plus: ^6.0.3
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/on_boarding_images/
    - assets/images/account_created/
    - assets//logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/loader/